--- 
- name: Download the latest OCP installer and oc client
  hosts: bastion
  gather_facts: false
  vars_files:
    - vars.yaml

  tasks: 

    - name: Copy in the install_config file to the install directory
      copy:
        src: files/install-config.yaml
        dest: "/root/ocp_install_{{ date }}/install-config.yaml"

    - name: Run the installer to generate the Kubernetes manifests for the cluster
      command: openshift-install create manifests --dir=/root/ocp_install_{{ date }}
      register: ocp_install_output

    - name: What all happened with openshift-install create manifests
      debug:
        var: ocp_install_output

    - name: make master nodes unschedulable
      lineinfile:
        path: /root/ocp_install_{{ date }}/manifests/cluster-scheduler-02-config.yml
        regexp: 'mastersSchedulable: true'
        line: 'mastersSchedulable: false'
        state: present

    - name: Run the installer to generate the vm ignition files
      command: openshift-install create ignition-configs --dir=/root/ocp_install_{{ date }}
      register: ocp_ignition_output

    - name: What all happened with openshift-install create ignition-configs
      debug:
        var: ocp_install_output

    - name: Copy over the ignition files from the Openshift Install directory on bastion
      fetch:
        src: "/root/ocp_install_{{ date }}/{{ item }}.ign"
        dest: "{{ image_dir }}"
        flat: yes
      loop:
        - bootstrap
        - worker
        - master
